### ISSUE TITLE
SPIN1_API: software transmit packet queue hazard

### ISSUE THREAD

**Issue by lplana** [SpiNNakerManchester/spinnaker_tools#115]
Function **spin1_send_packet** [spin1_api.c] is used to enqueue packets in **tx_packet_queue**. The function disables **irqs**, but not **fiqs**, while manipulating the **start** and **end** queue pointers.

There is a potential hazard in accessing these pointers if a fiq-level (-1) priority callback sends a packet. The hazard manifests when the callback interrupts **spin1_send_packet** and calls the same function to send its packet.

Although recommended practice is to reserve fiq-level priority for PACKET_RECEIVED events and restrict the callback to queueing the received packet, this is not enforced.

The obvious solution is to also disable **fiqs** in **spin1_send_packet**, potentially delaying PACKET_RECEIVED event processing . Needs evaluation.

**Comment by dkfellows** [comment]
Since the writing of control word, payload and key has to be an atomic action (to prevent garbling if nothing else) I would agree that turning off all interrupts (including FIQ) during the actual write is a good idea. It wouldn't be necessary if we could enforce that FIQs can't send messages, but I have no idea how we could do that and don't propose that we should try.

The strongly locked area probably should be very small. In particular, the lock must not be held if any delay is required.
